### ISSUE TITLE
Define NodeManager

### ISSUE THREAD

**Issue by pnlybubbles** [jThreeJS/jThree#108]
- [ ] Create NodeManager.
- [ ] Separate Goml node handler from GomlLoader and move to NodeManager.
- [ ] Separate Interface from JThreeContext and move to NodeManager.

**Comment by pnlybubbles** [comment]
- [ ] Separate `nodeRegister`
- [ ] Separate `append`
- [ ] Separate `instanciateTemplate`
- [ ] Separate parser

**Comment by LimeStreem** [comment]
Is this completed????

**Comment by pnlybubbles** [comment]
completed. I forgot.
