### ISSUE TITLE
An absolutely minimum interface 

### ISSUE THREAD

**Issue by pnlybubbles** [jThreeJS/jThree#239]
* [ ] animateを実装する
* [x] ImportNode　を実装する
* [ ] RenderStageのNode側とのバインド
* [x] GeometryRegistoryを利用してジオメトリを登録する
* [ ] on()　を実装する

**Comment by LimeStreem** [comment]
Import nodeの仕様
GOML内の記述方法
```xml
<goml>
   <imports>
      <import src="/test.xmml" type="material"/>
   </imports>
</goml>
```

* importsは他のどのルートノードよりも先に処理される。
* typeの指定がない場合は拡張子から判断する。
* 現状ではxmmlのみ。

XHRで解決したimport対象の中身を`MaterialManager#registerMaterial(中身:string)`を用いて登録する。

これに伴う、materialノードの仕様

```xml
<material name="jthree.testMaterial"/>
```

すべてのマテリアルはname属性を持つ。name属性に応じてMaterialManager#constructMaterial(name:string)を用いてマテリアルをインスタンス化する。

この際、すでに対象となるマテリアルはregisterMaterialされていなければならない。

* **一部、importになくてもデフォルトでregisterMaterialされているマテリアルがあることに注意**
* name以外の変数はMaterialBaseNodeの挙動により、すべてシェーダー側にフォワードされる。

**Comment by LimeStreem** [comment]
PrimitiveRegistoryを利用してジオメトリを記述する。
以後、以下のようなGOMLの記述をしなくてもいいようにする。

```xml
<goml>
   <resources>
      <cube name="cube"/>
      <sphere name="sphere"/>
   </resources>
</goml>
```

全てのjThreeの管理内にあるプリミティブはPrimitiveRegistoryによって管理される。
* PrimitiveRegistory#registerPrimitive(name:string,geo:Geometry)によってジオメトリは登録できる。
* 登録されたGeometryはPrimitiveRegistory#getPrimitive(name:string)によって取得可能。
* **すでに`name`がGeometryRegistoryに登録されている場合でも、registerPrimitiveを呼んでよい。デフォルトのPrimitiveを置き換えるための挙動である。**

以下のPrimitiveはデフォルトでPrimitiveRegisitoryに登録されている。(カッコ内はname)
* 立方体(cube)
* 筒(cylinder)
* 平面(quad)
* 球体(sphere)
* 円錐(cone)

**Comment by LimeStreem** [comment]
Issueを分割するべき

**Comment by LimeStreem** [comment]
重複のため削除
