### ISSUE TITLE
Module (旧 Behavior)

### ISSUE THREAD

**Issue by pnlybubbles** [jThreeJS/jThree#335]
# Module
* もともとBehaviorだったもの
* タグから利用可能だったものはだったものは分離し、中核の毎フレーム実行される処理をNodeに簡単に追加できるようにするだけ

## インターフェース
内部で使うことを目的としていたけど、いちおう用意した
```
j3("selector").module(MyModule);
```

### PlainObject
```js
var MyModule = {
  ratio: 0,
  update: function(node) {
    j3(node).attr('rotation', '0,' + this.ratio + ',0');
    this.ratio += 3;
  },
  start: function(node) {
    console.log('MyModule started', node);
  },
  terminate: function(node) {
    console.log('MyModule terminated', node);
  }
};
```
### es2015 Class
```js
class MyModule {
  constructor() {
    console.log('MyModule constructor');
    this.ratio = 0;
  }
  update(node) {
    j3(node).attr('rotation', '0,' + this.ratio + ',0');
    this.ratio += 3;
  }
  start(node) {
    console.log('MyModule started', node);
  }
  terminate(node) {
    console.log('MyModule terminated', node);
  }
}
```

**Comment by LimeStreem** [comment]
この仕様に関しては結構疑問。

Moduleの位置付けに関しては、多分Webエンジニアと3Dエンジニアの橋渡し的な役割をする部分だと思う。
Moduleを使う側は宣言的でイベント駆動で動作するべきであるが、Module内部に関してはループ駆動で動作するべき。この仕様は満たされているようではあるが、そう考えるとModuleを作成する側は3Dエンジニアやゲームエンジニアに近い存在になる。
Moduleの中でループ駆動な動作を要求されるのであれば、Nodeの操作よりコア側の操作によって成り立つべきではないのか。

**Comment by pnlybubbles** [comment]
現在のリビジョンではNodeの内部にモジュールの状態を保持するようになってます。
モジュールを作る側としてはモジュールのupdateの引数にコアのオブジェクトが入っていた方が適切？
```
update(coreObject, node)
```
とするのはどうでしょう。
nodeは一つのコアオブジェクトに結びついているので、そのコアオブジェクトを第一引数。
格納されているNodeを第二引数。

**Comment by LimeStreem** [comment]
まあいいんじゃないかな。
どうにかしてコア側の変更をnode側に反映するやつが欲しいところだけど、α版までには難しいかなーと思ってる。
