### ISSUE TITLE
remove bower

### ISSUE THREAD

**Issue by pnlybubbles** [jThreeJS/jThree#38]
* bowerとwebpackの親和性が良くない
* 利用しているbowerのパッケージがnpmに存在するため、npmとbowerを共存させる必要性が無い

これらの理由からbowerの削除を検討します

**Comment by LimeStreem** [comment]
![image](https://cloud.githubusercontent.com/assets/6434708/9190107/4ec44530-3fa6-11e5-8595-91d7c3ff15d9.png)

**Comment by pnlybubbles** [comment]
最新のコミットになっていない気がします
https://github.com/jThreeJS/jThree/commit/3b0c2993f0152f721e9964a8bce91ba380f405b5
