### ISSUE TITLE
Change bundler from webpack to browserify

### ISSUE THREAD

**Issue by pnlybubbles** [jThreeJS/jThree#42]
webpackの外部パッケージの依存解決の失敗の多さが問題。

webpackのバンドリングタスクも残しつつ、browserifyに移行していきたい。

まずテスト環境のみbrowserifyに移行するつもりだが、productのビルド環境とテスト環境が異なるというのは問題であるために、それに伴いproduct環境も移行する。

**Comment by LimeStreem** [comment]
これって結構時間かかりそうですかね？
