### ISSUE TITLE
Add unit test

### ISSUE THREAD

**Issue by LimeStreem** [jThreeJS/jThree#5]
# Add unit test....

**Comment by pnlybubbles** [comment]
testをtypescriptで導入しようという計画でしたが、mock domを扱うjsdomや、sinonなどのd.tsを書く必要性があり(tsdにあるものでは修正が必要)、typescriptの知識不足もありますが、testに型の恩恵は必要無いのではないかと考えています。

適材適所ということで初期のcoffee scriptでの導入に戻す方が良いのではないかと考えています。

**Comment by LimeStreem** [comment]
それでtestのコンパイルが通るならそれでいいです。まずは安定的に追加ができる効率的なテストの作成法を確立してください。

**Comment by LimeStreem** [comment]
タスクが大きすぎるので、分割して新しいタスクとして配分してください。
